#' Heatmap
#'
#' This function plots heatmaps dos metabólitos.
#' @export
#' @param myDir Path to the directory of work.
#' @param metadata A matrix or data.frame with metadata information about samples. Include, at least 'sample' and 'file' columns with name of sample and its path, respectively. More information can be added in new columns, such as 'group', 'class', 'biorep' and 'tecrep'.
#' @param n A normalized matrix generated by 'PipMet::normalize()'
#' @param colors A list with colors generated from "read_data()".
#' @return None.
#' @importFrom grDevices dev.off pdf png tiff
#' @importFrom graphics boxplot grid legend par text
#' @importFrom methods as new
#' @importFrom stats cor sd t.test var
#' @importFrom utils read.csv write.csv write.table
#' @importFrom pheatmap pheatmap
#' @examples
#' \dontrun{
#' load(system.file("extdata", "n.RData", package = "PipMet"))
#' load(system.file("extdata", "metadata.RData", package = "PipMet"))
#' load(system.file("extdata", "colors.RData", package = "PipMet"))
#' heatmap(n, metadata, myDir = "~/", colors)
#' }
#'
heatmap <- function(n, metadata, myDir, colors) {

  # set to statistic pictures folder
  if (!dir.exists("Statistics")) {
    dir.create("Statistics")
  }
  setwd("Statistics")

  mat <- n[, 6:ncol(n)] # remove aditional information from the normalized table of spectra
  mat <- apply(mat, MARGIN = 2, FUN = as.numeric)
  rownames(mat) <- n[, 1]

  # plot heatmap of metabolites per sample
  mat_scaled <- scale(mat)
  colnames(mat_scaled) <- metadata$all
  png("heatmap_scaled_geral.png", units = "cm", width = 16, height = 16, res = 900, bg = "NA")
  pheatmap(mat_scaled, cluster_rows = FALSE, main = "Heatmap of samples by spectra\n", fontsize_col = 5, fontsize_row = 5, show_rownames = FALSE, border_color = "NA")
  dev.off()
  tiff("heatmap_scaled_geral.tiff", units = "cm", width = 16, height = 16, res = 900, bg = "NA")
  pheatmap(mat_scaled, cluster_rows = FALSE, main = "Heatmap of samples by spectra\n", fontsize_col = 5, fontsize_row = 5, show_rownames = FALSE, border_color = "NA")
  dev.off()

  # only annotated metabolites per sample
  if (!sum(is.na(n[, 3])) <= 0) {
    mat_ident <- mat[-which(is.na(n[, 3])), ]
  } else {
    mat_ident <- mat
  }
  mat_ident_scaled <- scale(mat_ident)
  colnames(mat_ident_scaled) <- metadata$all
  rownames(mat_ident_scaled) <- n[-which(is.na(n[, 3])), 3]
  png("heatmap_scaled_ident.png", units = "cm", width = 16, height = 16, res = 900, bg = "NA")
  pheatmap(mat_ident_scaled, cluster_rows = FALSE, main = "Heatmap of samples by spectra\n", fontsize_col = 5, border_color = "NA", fontsize_row = 5)
  dev.off()
  tiff("heatmap_scaled_ident.tiff", units = "cm", width = 16, height = 16, res = 900, bg = "NA")
  pheatmap(mat_ident_scaled, cluster_rows = FALSE, main = "Heatmap of samples by spectra\n", fontsize_col = 5, border_color = "NA", fontsize_row = 5)
  dev.off()

  # calculate mean os technical replicates
  if ("tec_rep" %in% colnames(metadata)) {
    nhmedia <- matrix(nrow = nrow(mat), ncol = length(unique(metadata$tec_rep)))
    colnames(nhmedia) <- unique(metadata$tec_rep)
    for (i in unique(metadata$tec_rep)) {
      x <- grep(i, metadata$tec_rep)
      for (ii in 1:nrow(mat)) {
        nhmedia[ii, i] <- sum(mat[ii, x]) / length(x)
      }
    }
    nhmedia_scaled <- scale(nhmedia) # scale

    # add names of replicates
    for (i in 1:ncol(nhmedia_scaled)) {
      colnames(nhmedia_scaled)[i] <- metadata[(grep(colnames(nhmedia_scaled)[i], metadata$tec_rep))[1], "all"]
    }

    # plot heatmaps for ident + non_ident metabolites (MEAN)
    png("heatmap_repMean_scaled_geral.png", units = "cm", width = 16, height = 16, res = 900, bg = "NA")
    pheatmap(nhmedia_scaled, cluster_rows = FALSE, main = "Heatmap of samples by spectra\n", fontsize_col = 5, fontsize_row = 5)
    dev.off()
    tiff("heatmap_repMean_scaled_geral.tiff", units = "cm", width = 16, height = 16, res = 900, bg = "NA")
    pheatmap(nhmedia_scaled, cluster_rows = FALSE, main = "Heatmap of samples by spectra\n", fontsize_col = 5, fontsize_row = 5)
    dev.off()

    # only annotated metabolites (MEAN)
    mat_ident <- mat[-which(is.na(n[, 3])), ]
    nhmedia_ident <- matrix(nrow = nrow(mat_ident), ncol = length(unique(metadata$tec_rep)))
    colnames(nhmedia_ident) <- unique(metadata$all)
    rownames(nhmedia_ident) <- n[-which(is.na(n[, 3])), 3]
    for (i in unique(metadata$tec_rep)) {
      x <- grep(i, metadata$tec_rep)
      for (ii in 1:nrow(mat_ident)) {
        nhmedia_ident[ii, i] <- sum(mat_ident[ii, x]) / length(x)
      }
    }
    nhmedia_scaled_ident <- scale(nhmedia_ident) # scale

    # plot heatmaps
    for (i in 1:length(colors)) {
      # png
      png(paste0("heatmap_repMean_scaled_ident_unique", names(colors)[i], ".png"), units = "cm", width = 16, height = 16, res = 900, bg = "NA")
      pheatmap(nhmedia_scaled_ident, cluster_rows = FALSE, main = "Heatmap of samples by spectra\n", fontsize_row = 5, fontsize_col = 5, annotation_colors = list(class = colors[[i]][[2]]), border_color = "NA")
      dev.off()
      # tiff
      tiff(paste0("heatmap_repMean_scaled_ident_unique", names(colors)[i], ".tiff"), units = "cm", width = 16, height = 16, res = 900, bg = "NA")
      pheatmap(nhmedia_scaled_ident, cluster_rows = FALSE, main = "Heatmap of samples by spectra\n", fontsize_row = 5, fontsize_col = 5, annotation_colors = list(class = colors[[i]][[2]]), border_color = "NA")
      dev.off()
    }
  }

  # back to main folder
  setwd(myDir)
}
