#' PCA
#'
#' This function plots PCA.
#' @export
#' @param myDir Path to the directory of work.
#' @param metadata A matrix or data.frame with metadata information about samples. Include, at least 'sample' and 'file' columns with name of sample and its path, respectively. More information can be added in new columns, such as 'group', 'class', 'biorep' and 'tecrep'.
#' @param colors A list with colors generated from "read_data()"
#' @param n A normalized matrix generated by 'PipMet::normalize()'
#' @return None.
#' @importFrom grDevices dev.off pdf png tiff
#' @importFrom graphics boxplot grid legend par text
#' @importFrom methods as new
#' @importFrom stats cor sd t.test var prcomp na.omit
#' @importFrom utils menu read.csv select.list write.csv write.table
#' @import ggplot2
#' @importFrom ggrepel geom_text_repel
#' @examples
#' \dontrun{
#' load(system.file("extdata", "n.RData", package = "PipMet"))
#' load(system.file("extdata", "colors.RData", package = "PipMet"))
#' load(system.file("extdata", "metadata.RData", package = "PipMet"))
#' PCA_(n, metadata, myDir = "~/", colors)
#' }
#'
PCA_ <- function(n, metadata, myDir, colors) {
  mat <- n[, 6:ncol(n)] # remove aditional information from the normalized table of spectra
  mat <- apply(mat, MARGIN = 2, FUN = as.numeric)
  rownames(mat) <- n[, 1]

  # new folder for PCA results
  if (!dir.exists("PCA")) {
    dir.create("PCA")
  }
  setwd("PCA")

  if (!"metadata$all" %in% colnames(metadata)) {
    # create 'metadata$all' 1 and 2 for identification
    x <- colnames(metadata)
    for (i in c("sample", "tec_rep", "bio_rep", "file", "all", "all2")) {
      if (i %in% x) {
        x <- x[-which(x == i)]
      }
    }
    if (length(x) > 1) {
      for (i in 1:nrow(metadata)) {
        f <- metadata[i, x[[1]]]
        for (ii in 2:length(x)) {
          f <- paste0(f, "_", metadata[i, x[[ii]]])
        }
        metadata[i, "all"] <- f
        metadata$all2[i] <- paste0(i, " - ", metadata$all[i])
      }
    } else {
      metadata$all <- metadata[, x]
      metadata$all2 <- paste0(c(1:nrow(metadata)), " - ", metadata$all)
    }
  }

  # set for PCA calculations
  pc <- prcomp(t(na.omit(mat[, 1:nrow(metadata)])), center = TRUE)
  pcSummary <- summary(pc)
  for (i in 1:length(colors)) {
    # png
    png(paste0("PCA_", names(colors)[[i]], ".png"), units = "cm", width = 16, height = 16, res = 900, bg = "NA")
    print(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1], y = pc$x[, 2], color = colors[[i]][[1]])) +
      geom_point(size = 3, shape = 20) +
      theme_minimal() +
      labs(title = "PCA", x = paste0("PC1: ", format(pcSummary$importance[2, 1] * 100, digits = 3), " % variance"), y = paste0("PC2: ", format(pcSummary$importance[2, 2] * 100, digits = 3), " % variance"), fill = names(colors)[[i]], colour = names(colors)[[i]]) +
      stat_ellipse(geom = "polygon", aes(fill = colors[[i]][[1]]), alpha = 0.25) +
      theme(rect = element_rect(fill = "transparent"), plot.title = element_text(hjust = 0.5, color = "black", size = 16, face = "bold")))
    dev.off()
    png(paste0("PCA_named_", names(colors)[[i]], ".png"), units = "cm", width = 16, height = 16, res = 900, bg = "NA")
    print(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1], y = pc$x[, 2], label = metadata$all, color = colors[[i]][[1]])) +
      geom_point(size = 3, shape = 20) +
      theme_minimal() +
      labs(title = "PCA", x = paste0("PC1: ", format(pcSummary$importance[2, 1] * 100, digits = 3), " % variance"), y = paste0("PC2: ", format(pcSummary$importance[2, 2] * 100, digits = 3), " % variance"), fill = names(colors)[[i]], colour = names(colors)[[i]]) +
      stat_ellipse(geom = "polygon", aes(fill = colors[[i]][[1]]), alpha = 0.10) +
      theme(rect = element_rect(fill = "transparent"), plot.title = element_text(hjust = 0.5, color = "black", size = 16, face = "bold")) +
      geom_text_repel())
    dev.off()
    # tiff
    tiff(paste0("PCA_", names(colors)[[i]], ".tiff"), units = "cm", width = 16, height = 16, res = 900, bg = "NA")
    print(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1], y = pc$x[, 2], color = colors[[i]][[1]])) +
      geom_point(size = 3, shape = 20) +
      theme_minimal() +
      labs(title = "PCA", x = paste0("PC1: ", format(pcSummary$importance[2, 1] * 100, digits = 3), " % variance"), y = paste0("PC2: ", format(pcSummary$importance[2, 2] * 100, digits = 3), " % variance"), fill = names(colors)[[i]], colour = names(colors)[[i]]) +
      stat_ellipse(geom = "polygon", aes(fill = colors[[i]][[1]]), alpha = 0.25) +
      theme(rect = element_rect(fill = "transparent"), plot.title = element_text(hjust = 0.5, color = "black", size = 16, face = "bold")))
    dev.off()
    tiff(paste0("PCA_named_", names(colors)[[i]], ".tiff"), units = "cm", width = 16, height = 16, res = 900, bg = "NA")
    print(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1], y = pc$x[, 2], label = metadata$all, color = colors[[i]][[1]])) +
      geom_point(size = 3, shape = 20) +
      theme_minimal() +
      labs(title = "PCA", x = paste0("PC1: ", format(pcSummary$importance[2, 1] * 100, digits = 3), " % variance"), y = paste0("PC2: ", format(pcSummary$importance[2, 2] * 100, digits = 3), " % variance"), fill = names(colors)[[i]], colour = names(colors)[[i]]) +
      stat_ellipse(geom = "polygon", aes(fill = colors[[i]][[1]]), alpha = 0.10) +
      theme(rect = element_rect(fill = "transparent"), plot.title = element_text(hjust = 0.5, color = "black", size = 16, face = "bold")) +
      geom_text_repel())
    dev.off()
  }

  # set to main folder
  setwd(myDir)
}
