#' PCA_general
#'
#' This function plots PCA.
#' @export
#' @param myDir Path to the directory of work.
#' @param example Only for software testing. No pictures will be created.
#' @param metadata A matrix or data.frame with metadata information about samples. Include, at least 'sample' and 'file' columns with name of sample and its path, respectively. More information can be added in new columns, such as 'group', 'class', 'biorep' and 'tecrep'.
#' @param colors A list with colors generated from 'read_data()'
#' @param n A normalized matrix generated by 'PipMet::normalize()'
#' @param example Logical. If is example, pop-ups won't appear. Default to FALSE.
#' @param pic_extension Character. Pictures format to generate. Supported = '.tiff', '.png'. Default to c('.tiff', '.png').
#' @return None.
#' @importFrom grDevices dev.off pdf png tiff
#' @importFrom graphics boxplot grid legend par text
#' @importFrom stringr str_c
#' @importFrom methods as new
#' @importFrom stats cor sd t.test var prcomp na.omit
#' @importFrom utils menu read.csv select.list write.csv write.table
#' @import ggplot2
#' @importFrom ggrepel geom_text_repel
#' @examples
#' \donttest{
#' \dontrun{
#' load(system.file('extdata', 'n.RData', package = 'PipMet'))
#' load(system.file('extdata', 'colors.RData', package = 'PipMet'))
#' load(system.file('extdata', 'metadata.RData', package = 'PipMet'))
#' PCA_general(n, metadata, colors = colors, example = TRUE)
#' }
#'}
PCA_general <- function(n, metadata, myDir, colors, pic_extension = c(".tiff",
    ".png"), example = FALSE) {

    mat <- n[, 6:ncol(n)]  # remove aditional information from the normalized table of spectra
    mat <- apply(mat, MARGIN = 2, FUN = as.numeric)
    rownames(mat) <- n[, 1]

    # new folder for PCA results
    if (!example == TRUE) {
        setwd(myDir)
        if (!dir.exists("PCA_general")) {
            dir.create("PCA_general")
        }
        setwd("PCA_general")
    }

    # all samples togheter set for PCA calculations
    pc <- prcomp(t(na.omit(mat[, seq_len(nrow(metadata))])), center = TRUE)
    pcSummary <- summary(pc)
    for (i in seq_len(length(colors))) {

        # png
        if (".png" %in% pic_extension & !example == TRUE) {
            png(str_c("PCA_", names(colors)[[i]], ".png"), units = "cm", width = 16,
                height = 16, res = 900, bg = "NA")
            plot(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1],
                y = pc$x[, 2], color = colors[[i]][[1]])) + geom_point(size = 3,
                shape = 20) + theme_minimal() + labs(title = "PCA", x = str_c("PC1: ",
                format(pcSummary$importance[2, 1] * 100, digits = 3), " % variance"),
                y = str_c("PC2: ", format(pcSummary$importance[2, 2] * 100,
                  digits = 3), " % variance"), fill = names(colors)[[i]], colour = names(colors)[[i]]) +
                stat_ellipse(geom = "polygon", aes(fill = colors[[i]][[1]]),
                  alpha = 0.25) + theme(rect = element_rect(fill = "transparent"),
                plot.title = element_text(hjust = 0.5, color = "black", size = 16,
                  face = "bold")))
            dev.off()
            png(str_c("PCA_named_", names(colors)[[i]], ".png"), units = "cm",
                width = 16, height = 16, res = 900, bg = "NA")
            plot(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1],
                y = pc$x[, 2], label = metadata$sample, color = colors[[i]][[1]])) +
                geom_point(size = 3, shape = 20) + theme_minimal() + labs(title = "PCA",
                x = str_c("PC1: ", format(pcSummary$importance[2, 1] * 100,
                  digits = 3), " % variance"), y = str_c("PC2: ", format(pcSummary$importance[2,
                  2] * 100, digits = 3), " % variance"), fill = names(colors)[[i]],
                colour = names(colors)[[i]]) + stat_ellipse(geom = "polygon",
                aes(fill = colors[[i]][[1]]), alpha = 0.1) + theme(rect = element_rect(fill = "transparent"),
                plot.title = element_text(hjust = 0.5, color = "black", size = 16,
                  face = "bold")) + geom_text_repel())
            dev.off()
        }

        # tiff
        if (".tiff" %in% pic_extension & !example == TRUE) {
            tiff(str_c("PCA_", names(colors)[[i]], ".tiff"), units = "cm", width = 16,
                height = 16, res = 900, bg = "NA")
            plot(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1],
                y = pc$x[, 2], color = colors[[i]][[1]])) + geom_point(size = 3,
                shape = 20) + theme_minimal() + labs(title = "PCA", x = str_c("PC1: ",
                format(pcSummary$importance[2, 1] * 100, digits = 3), " % variance"),
                y = str_c("PC2: ", format(pcSummary$importance[2, 2] * 100,
                  digits = 3), " % variance"), fill = names(colors)[[i]], colour = names(colors)[[i]]) +
                stat_ellipse(geom = "polygon", aes(fill = colors[[i]][[1]]),
                  alpha = 0.25) + theme(rect = element_rect(fill = "transparent"),
                plot.title = element_text(hjust = 0.5, color = "black", size = 16,
                  face = "bold")))
            dev.off()
            tiff(str_c("PCA_named_", names(colors)[[i]], ".tiff"), units = "cm",
                width = 16, height = 16, res = 900, bg = "NA")
            plot(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1],
                y = pc$x[, 2], label = metadata$sample, color = colors[[i]][[1]])) +
                geom_point(size = 3, shape = 20) + theme_minimal() + labs(title = "PCA",
                x = str_c("PC1: ", format(pcSummary$importance[2, 1] * 100,
                  digits = 3), " % variance"), y = str_c("PC2: ", format(pcSummary$importance[2,
                  2] * 100, digits = 3), " % variance"), fill = names(colors)[[i]],
                colour = names(colors)[[i]]) + stat_ellipse(geom = "polygon",
                aes(fill = colors[[i]][[1]]), alpha = 0.1) + theme(rect = element_rect(fill = "transparent"),
                plot.title = element_text(hjust = 0.5, color = "black", size = 16,
                  face = "bold")) + geom_text_repel())
            dev.off()
        }
    }

    # Ask for a particular sort of sample
    if (!example == TRUE) {
        group <- dlg_list(names(metadata), multiple = FALSE, title = "Condition to PCA:")$res
        subgroup <- dlg_list(as.character(unique(metadata[, group])), multiple = TRUE,
            title = "Condition to PCA:")$res
    } else {
        group <- "group"
        subgroup <- c("Sugar", "Energy")
    }

    # get intensities only from selected columns (samples)
    z <- vector()
    for (i in seq_len(length(subgroup))) {
        z <- c(z, which(metadata[, group] == subgroup[[i]]))
    }
    mat_selected <- mat[, z]
    pc <- prcomp(t(na.omit(mat[, metadata$sample[z]])), center = TRUE)
    pcSummary <- summary(pc)

    if (!example == TRUE) {
        if (!dir.exists(group)) {
            dir.create(group)
        }
        setwd(group)
    }

    for (i in seq_len(length(colors))) {
        # png
        if (".png" %in% pic_extension & !example == TRUE) {
            png(str_c("PCAselected_", names(colors)[[i]], ".png"), units = "cm",
                width = 16, height = 16, res = 900, bg = "NA")
            plot(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1],
                y = pc$x[, 2], color = colors[[i]][[1]][z])) + geom_point(size = 3,
                shape = 20) + theme_minimal() + labs(title = "PCA", x = str_c("PC1: ",
                format(pcSummary$importance[2, 1] * 100, digits = 3), " % variance"),
                y = str_c("PC2: ", format(pcSummary$importance[2, 2] * 100,
                  digits = 3), " % variance"), fill = names(colors)[[i]], colour = names(colors)[[i]]) +
                stat_ellipse(geom = "polygon", aes(fill = colors[[i]][[1]][z]),
                  alpha = 0.25) + theme(rect = element_rect(fill = "transparent"),
                plot.title = element_text(hjust = 0.5, color = "black", size = 16,
                  face = "bold")))
            dev.off()
            png(str_c("PCAselected_named_", names(colors)[[i]], ".png"), units = "cm",
                width = 16, height = 16, res = 900, bg = "NA")
            plot(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1],
                y = pc$x[, 2], label = metadata$sample[z], color = colors[[i]][[1]][z])) +
                geom_point(size = 3, shape = 20) + theme_minimal() + labs(title = "PCA",
                x = str_c("PC1: ", format(pcSummary$importance[2, 1] * 100,
                  digits = 3), " % variance"), y = str_c("PC2: ", format(pcSummary$importance[2,
                  2] * 100, digits = 3), " % variance"), fill = names(colors)[[i]],
                colour = names(colors)[[i]]) + stat_ellipse(geom = "polygon",
                aes(fill = colors[[i]][[1]][z]), alpha = 0.1) + theme(rect = element_rect(fill = "transparent"),
                plot.title = element_text(hjust = 0.5, color = "black", size = 16,
                  face = "bold")) + geom_text_repel())
            dev.off()
        }

        # tiff
        if (".tiff" %in% pic_extension & !example == TRUE) {
            tiff(str_c("PCAselected_", names(colors)[[i]], ".tiff"), units = "cm",
                width = 16, height = 16, res = 900, bg = "NA")
            plot(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1],
                y = pc$x[, 2], color = colors[[i]][[1]][z])) + geom_point(size = 3,
                shape = 20) + theme_minimal() + labs(title = "PCA", x = str_c("PC1: ",
                format(pcSummary$importance[2, 1] * 100, digits = 3), " % variance"),
                y = str_c("PC2: ", format(pcSummary$importance[2, 2] * 100,
                  digits = 3), " % variance"), fill = names(colors)[[i]], colour = names(colors)[[i]]) +
                stat_ellipse(geom = "polygon", aes(fill = colors[[i]][[1]][z]),
                  alpha = 0.25) + theme(rect = element_rect(fill = "transparent"),
                plot.title = element_text(hjust = 0.5, color = "black", size = 16,
                  face = "bold")))
            dev.off()
            tiff(str_c("PCAselected_named_", names(colors)[[i]], ".tiff"), units = "cm",
                width = 16, height = 16, res = 900, bg = "NA")
            plot(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1],
                y = pc$x[, 2], label = metadata$sample[z], color = colors[[i]][[1]][z])) +
                geom_point(size = 3, shape = 20) + theme_minimal() + labs(title = "PCA",
                x = str_c("PC1: ", format(pcSummary$importance[2, 1] * 100,
                  digits = 3), " % variance"), y = str_c("PC2: ", format(pcSummary$importance[2,
                  2] * 100, digits = 3), " % variance"), fill = names(colors)[[i]],
                colour = names(colors)[[i]]) + stat_ellipse(geom = "polygon",
                aes(fill = colors[[i]][[1]][z]), alpha = 0.1) + theme(rect = element_rect(fill = "transparent"),
                plot.title = element_text(hjust = 0.5, color = "black", size = 16,
                  face = "bold")) + geom_text_repel())
            dev.off()
        }
    }
    # set to main folder
    if (!example == TRUE) {
        setwd(myDir)
    }
}
