#' PCA
#'
#' This function plots PCA.
#' @export
#' @param myDir Path to the directory of work.
#' @param metadata A matrix or data.frame with metadata information about samples. Include, at least 'sample' and 'file' columns with name of sample and its path, respectively. More information can be added in new columns, such as 'group', 'class', 'biorep' and 'tecrep'.
#' @param mat Matrix of normalized intensities generated by 'PipMet::vol_lvl1()'.
#' @param colors A list with colors generated from "read_data()".
#' @return None.
#' @importFrom grDevices dev.off pdf png tiff
#' @importFrom graphics boxplot grid legend par text
#' @importFrom methods as new
#' @importFrom stats cor sd t.test var prcomp na.omit
#' @importFrom utils menu read.csv select.list write.csv write.table
#' @import ggplot2
#' @importFrom ggrepel geom_text_repel
#' @examples
#' \dontrun{
#' PCA_(mat, metadata, myDir, colors)
#' }

PCA_ <- function(mat, metadata, myDir, colors) {

  # new folder for PCA results
  dir.create("PCA")
  setwd("PCA")

  # set for PCA calculations
  pc <- prcomp(t(na.omit(mat[, 1:nrow(metadata)])), center = TRUE)
  pcSummary <- summary(pc)
  for (i in 1:length(colors)) {
    # png
    png(paste0("PCA_", names(colors)[[i]], ".png"), units = "cm", width = 16, height = 16, res = 1500, bg = "NA")
    print(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1], y = pc$x[, 2], color = colors[[i]][[1]])) +
      geom_point(size = 3, shape = 20) +
      theme_minimal() +
      labs(title = "PCA", x = paste0("PC1: ", format(pcSummary$importance[2, 1] * 100, digits = 3), " % variance"), y = paste0("PC2: ", format(pcSummary$importance[2, 2] * 100, digits = 3), " % variance"), fill = names(colors)[[i]], colour = names(colors)[[i]]) +
      stat_ellipse(geom = "polygon", aes(fill = colors[[i]][[1]]), alpha = 0.25) +
      theme(rect = element_rect(fill = "transparent"), plot.title = element_text(hjust = 0.5, color = "black", size = 16, face = "bold")))
    dev.off()
    png(paste0("PCA_named_", names(colors)[[i]], ".png"), units = "cm", width = 16, height = 16, res = 1500, bg = "NA")
    print(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1], y = pc$x[, 2], label = metadata$all, color = colors[[i]][[1]])) +
      geom_point(size = 3, shape = 20) +
      theme_minimal() +
      labs(title = "PCA", x = paste0("PC1: ", format(pcSummary$importance[2, 1] * 100, digits = 3), " % variance"), y = paste0("PC2: ", format(pcSummary$importance[2, 2] * 100, digits = 3), " % variance"), fill = names(colors)[[i]], colour = names(colors)[[i]]) +
      stat_ellipse(geom = "polygon", aes(fill = colors[[i]][[1]]), alpha = 0.10) +
      theme(rect = element_rect(fill = "transparent"), plot.title = element_text(hjust = 0.5, color = "black", size = 16, face = "bold")) +
      geom_text_repel())
    dev.off()
    # tiff
    tiff(paste0("PCA_", names(colors)[[i]], ".tiff"), units = "cm", width = 16, height = 16, res = 1500, bg = "NA")
    print(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1], y = pc$x[, 2], color = colors[[i]][[1]])) +
      geom_point(size = 3, shape = 20) +
      theme_minimal() +
      labs(title = "PCA", x = paste0("PC1: ", format(pcSummary$importance[2, 1] * 100, digits = 3), " % variance"), y = paste0("PC2: ", format(pcSummary$importance[2, 2] * 100, digits = 3), " % variance"), fill = names(colors)[[i]], colour = names(colors)[[i]]) +
      stat_ellipse(geom = "polygon", aes(fill = colors[[i]][[1]]), alpha = 0.25) +
      theme(rect = element_rect(fill = "transparent"), plot.title = element_text(hjust = 0.5, color = "black", size = 16, face = "bold")))
    dev.off()
    tiff(paste0("PCA_named_", names(colors)[[i]], ".tiff"), units = "cm", width = 16, height = 16, res = 1500, bg = "NA")
    print(ggplot(data = as.data.frame.array(pc$x), aes(x = pc$x[, 1], y = pc$x[, 2], label = metadata$all, color = colors[[i]][[1]])) +
      geom_point(size = 3, shape = 20) +
      theme_minimal() +
      labs(title = "PCA", x = paste0("PC1: ", format(pcSummary$importance[2, 1] * 100, digits = 3), " % variance"), y = paste0("PC2: ", format(pcSummary$importance[2, 2] * 100, digits = 3), " % variance"), fill = names(colors)[[i]], colour = names(colors)[[i]]) +
      stat_ellipse(geom = "polygon", aes(fill = colors[[i]][[1]]), alpha = 0.10) +
      theme(rect = element_rect(fill = "transparent"), plot.title = element_text(hjust = 0.5, color = "black", size = 16, face = "bold")) +
      geom_text_repel())
    dev.off()
  }

  # set to main folder
  setwd(myDir)
}
