#' Statistics figures
#'
#' This function plots volcanos .
#' @export
#' @param myDir Path to the directory of work.
#' @param metadata A matrix or data.frame with metadata information about samples. Include, at least 'sample' and 'file' columns with name of sample and its path, respectively. More information can be added in new columns, such as 'group', 'class', 'biorep' and 'tecrep'.
#' @param n A normalized matrix generated by 'PipMet::normalize()'
#' @return A directory for volcano plots.
#' @importFrom grDevices dev.off pdf png tiff
#' @importFrom graphics boxplot grid legend par text
#' @importFrom stats cor sd t.test var
#' @importFrom utils menu read.csv select.list write.csv write.table
#' @import ggplot2
#' @importFrom ggrepel geom_text_repel
#' @examples
#' \dontrun{
#' load(system.file("extdata", "n.RData", package = "PipMet"))
#' load(system.file("extdata", "metadata.RData", package = "PipMet"))
#' vol_lvl1(n, metadata, myDir = "~/")
#' }
#'
vol_lvl1 <- function(n, metadata, myDir) {
  mat <- n[, 6:ncol(n)] # remove aditional information from the normalized table of spectra
  mat <- apply(mat, MARGIN = 2, FUN = as.numeric)
  rownames(mat) <- n[, 1]

  if (!dir.exists("Statistics") == TRUE) {
    dir.create("Statistics")
  }
  setwd("Statistics")
  if (!dir.exists("Volcanos") == TRUE) {
    dir.create("Volcanos")
  }
  setwd("Volcanos")

  volDir <- getwd()
  x <- menu(names(metadata), graphics = TRUE, title = "Choose a condition to compare") # ask condition to compare from the metadata table
  opt <- select.list(as.character(unique(metadata[, as.integer(x)])), preselect = NULL, multiple = TRUE, title = "Select two characteristic to compare", graphics = TRUE) # from that condition, which characteristics to compare
  first <- grep(opt[1], metadata[, (as.integer(x))], fixed = TRUE)
  sec <- grep(opt[2], metadata[, (as.integer(x))], fixed = TRUE)

  # create folder for comparison
  dir.create(paste0(opt[1], " X ", opt[2]))
  setwd(paste0(opt[1], " X ", opt[2]))
  # rawpvalue <- apply(mat, 1, ttest, grp1 = first, grp2 = sec) # calculate ttest

  rawpvalue <- matrix(nrow = nrow(mat), ncol = 1)
  # calculate t test
  for (i in 1:nrow(mat)) {
    rawpvalue[[i]] <- t.test(as.numeric(mat[i, first]), as.numeric(mat[i, sec]))$p.value
  }

  # calculates foldchange and plot histogram
  firstCond <- apply(mat[, first], 1, mean)
  secCond <- apply(mat[, sec], 1, mean)
  foldchange <- firstCond - secCond
  de <- as.data.frame(cbind(foldchange, rawpvalue))
  for (i in 1:nrow(n)) {
    if (is.na(n[i, 3])) {
      de$spcId[i] <- n[i, 1]
    } else {
      de$spcId[i] <- n[i, 3]
    }
  } # add annotation if present

  # add identification for relative abundance (Unchanged, Up or Down)
  de$Relative_abundance <- "Unchanged"
  de$Relative_abundance[de$foldchange > 0.6 & de$rawpvalue < 0.05] <- "Up"
  de$Relative_abundance[de$foldchange < -0.6 & de$rawpvalue < 0.05] <- "Down"

  # plot volcanos without identification
  a <- ggplot(data = de, aes(x = foldchange, y = -log10(rawpvalue), col = de$Relative_abundance)) +
    geom_point() +
    theme_minimal() +
    geom_vline(xintercept = c(-0.6, 0.6), col = "red") +
    geom_hline(yintercept = -log10(0.05), col = "red") +
    ggtitle(label = paste0(opt[1], " X ", opt[2])) +
    theme(rect = element_rect(fill = "transparent"), plot.title = element_text(hjust = 0.5, color = "black"))

  png("volcano.png", units = "cm", width = 16, height = 16, res = 900, bg = "NA")
  gridExtra::grid.arrange(a)
  dev.off()
  tiff("volcano.tiff", units = "cm", width = 16, height = 16, res = 900, bg = "NA")
  gridExtra::grid.arrange(a)
  dev.off()

  # plot volcanos with identification
  de$delabel <- NA
  de$delabel[de$Relative_abundance != "Unchanged"] <- de$spcId[de$Relative_abundance != "Unchanged"]
  b <- ggplot(data = de, aes(x = foldchange, y = -log10(rawpvalue), col = de$Relative_abundance, label = de$delabel)) +
    geom_point() +
    ggtitle(label = paste0(opt[1], " X ", opt[2])) +
    theme_minimal() +
    geom_vline(xintercept = c(-0.6, 0.6), col = "red") +
    geom_hline(yintercept = -log10(0.05), col = "red") +
    geom_text_repel() +
    theme(rect = element_rect(fill = "transparent"), plot.title = element_text(hjust = 0.5, color = "black")) +
    xlab("Log2 Mean Fold Change") +
    ylab("-Log10 pValue")
  png("volcano_identified.png", units = "cm", width = 16, height = 16, res = 900, bg = "NA")
  gridExtra::grid.arrange(b)
  dev.off()
  tiff("volcano_identified.tiff", units = "cm", width = 16, height = 16, res = 900, bg = "NA")
  gridExtra::grid.arrange(b)
  dev.off()

  # set to main folder
  setwd(volDir)
  setwd(myDir)

  # return results
  return(volDir)
}
